# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: babylog_stream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62\x61\x62ylog_stream.proto\x12\x0e\x62\x61\x62ylog_stream\"M\n\x0bVisionModel\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.babylog_stream.VisionModelType\x12\x0f\n\x07version\x18\x02 \x01(\t\"L\n\rDeviceDetails\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x17\n\ngroup_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_group_name\"_\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x15\n\x08\x63hannels\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x0bimage_bytes\x18\x04 \x01(\x0c\x42\x0b\n\t_channels\"f\n\nImageBatch\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x12\n\nbatch_size\x18\x04 \x01(\x05\x12\x13\n\x0bimage_bytes\x18\x05 \x01(\x0c\"c\n\x14\x43lassificationResult\x12\x15\n\x08\x63lass_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\x02\x42\x0b\n\t_class_id\"j\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x17\n\nconfidence\x18\x05 \x01(\x02H\x00\x88\x01\x01\x42\r\n\x0b_confidence\"\xd9\x02\n\x15SingleImagePrediction\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x35\n\x0e\x64\x65vice_details\x18\x02 \x01(\x0b\x32\x1d.babylog_stream.DeviceDetails\x12*\n\x05model\x18\x03 \x01(\x0b\x32\x1b.babylog_stream.VisionModel\x12(\n\traw_image\x18\x04 \x01(\x0b\x32\x15.babylog_stream.Image\x12\x17\n\nprediction\x18\x05 \x01(\x0cH\x00\x88\x01\x01\x12\x43\n\x15\x63lassification_result\x18\x06 \x03(\x0b\x32$.babylog_stream.ClassificationResult\x12\x33\n\x0e\x62ounding_boxes\x18\x07 \x03(\x0b\x32\x1b.babylog_stream.BoundingBoxB\r\n\x0b_prediction*4\n\x0fVisionModelType\x12\x12\n\x0e\x43LASSIFICATION\x10\x00\x12\r\n\tDETECTION\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'babylog_stream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VISIONMODELTYPE._serialized_start=955
  _VISIONMODELTYPE._serialized_end=1007
  _VISIONMODEL._serialized_start=40
  _VISIONMODEL._serialized_end=117
  _DEVICEDETAILS._serialized_start=119
  _DEVICEDETAILS._serialized_end=195
  _IMAGE._serialized_start=197
  _IMAGE._serialized_end=292
  _IMAGEBATCH._serialized_start=294
  _IMAGEBATCH._serialized_end=396
  _CLASSIFICATIONRESULT._serialized_start=398
  _CLASSIFICATIONRESULT._serialized_end=497
  _BOUNDINGBOX._serialized_start=499
  _BOUNDINGBOX._serialized_end=605
  _SINGLEIMAGEPREDICTION._serialized_start=608
  _SINGLEIMAGEPREDICTION._serialized_end=953
# @@protoc_insertion_point(module_scope)
